### ISSUE TITLE
ノート画面への遷移に時間がかかる

### ISSUE THREAD

**Issue by azumag** [kanoinfonet/annotter_alpha#2]
chrome 版あのったレットでノート記入画面を呼び出したときの体感は5秒ほどで，
ストレスを感じる時がある（さっと表示してさっと記入したいときなど）
（実際は 2000-3000ms?）
でもこれは，α 版のための弱めインスタンスでサービスが動いてるため？かもしれません

**Comment by kanoinfonet** [comment]
こちらのログを見るとリクエスト処理時間が最悪で600msくらい、ほとんどが200msに収まってますので、多分タブを開く時間と通信時間ですね…

さっとノートをつけるには通信は要らないので、あのったレットのポップアップでノートを書けるようにすべきでしょうね

**Comment by kanoinfonet** [comment]
とりあえずフォームを用意しました。どうでしょう→ [あのったレット0.9.2版](https://github.com/kanoinfonet/annotter_firefox_addon/releases/tag/0.9.2)

cmd-enter #4 はここにもほしいですね。次の更新で入れます。

**Comment by kanoinfonet** [comment]
入れました:grinning:
