### ISSUE TITLE
[UX] cmd+returnでノート投稿したい

### ISSUE THREAD

**Issue by azumag** [kanoinfonet/annotter_alpha#4]
コメントだけ書いてすぐ投稿したい場合，カーソルを動かすのがストレスとなるので

**Comment by kanoinfonet** [comment]
とりあえずブラウザ拡張機能では対応しました→[0.9.2.1版](https://github.com/kanoinfonet/annotter_firefox_addon/releases/tag/0.9.2.1)

**Comment by kanoinfonet** [comment]
buggyだったかも:sweat_drops: こちらを使って下さい:bow:→ [0.9.2.2版](https://github.com/kanoinfonet/annotter_firefox_addon/releases/tag/0.9.2.2)

**Comment by azumag** [comment]
少し使ってみた所，快適動作で良い感じだと思います！（Chrome 版）
