### ISSUE TITLE
ログイン後リダイレクトで 400 エラーが出た

### ISSUE THREAD

**Issue by azumag** [kanoinfonet/annotter_alpha#6]
アクセス日付・時刻は `2017-08-03 3:01:00` 頃です．
webのトップページ `https://annotter.com/` -> ログイン -> 自動で認証 -> リダイレクト（ここでエラー）
<img width="1266" alt="2017-08-03 3 01 46" src="https://user-images.githubusercontent.com/9018513/28887498-57888f3c-77f8-11e7-8f94-f56fac539258.png">

**Comment by azumag** [comment]
尚，ブラウザバックして再度同じ操作をすると出ない．
ログアウトして再度同じ操作をしても出なかった．
出る条件がいまいちわからない．

**Comment by kanoinfonet** [comment]
レポートありがとう。あのったレットの不具合による症状のようです。例えば以下の手順で再現すると思います。

1. あのったーからログアウトした状態にする
2. ツイッターであのったーへのあぷり
2. ブラウザのhttpとかhttpsとかでないタブ（about:とか）であのったレットのアイコンをクリック
3. 「ノート一覧」をクリック

「ノート一覧」リンクを無効にする必要がありそうです。対応します。

**Comment by kanoinfonet** [comment]
あのったレット0.9.6で対応しました。
